name: "CI"
on:
  push:
    paths:
      - "src/**"
      - "test/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            hugo-node: ./**/hugo-node/**

  smoketest:
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.templates }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"

  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "false"
          validate-only: ""
          base-path-to-templates: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
