name: "Generate/Update Docs"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/src"

jobs:
  generate:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "false" # generating only
          base-path-to-templates: "./src"
          generate-docs: "true"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Short SHA
        uses: hudsonm62/short-sha@v1
        id: short-sha

      - name: Create PR for Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."

          # Configure git and Push updates
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false

          branch=automated-documentation-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated documentation update - ${{ steps.short-sha.outputs.sha }}'

          # Add / update and commit
          git add */**/README.md
          git commit -m 'Automated documentation update [skip ci]' || export NO_UPDATES=true

          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message" --head $(git branch --show-current)
          fi
